### ISSUE TITLE
Data recorded in a table or in user session only?

### ISSUE THREAD

**Issue by migmake** [mattgrayisok/craft-recently-viewed#5]
I tried your great plugin but I feel the data are only recorded in the user session because when I lose my session or when I change browser I cannot retrieve my recently viewed infos. Start from zero again.

The plugin datas are only stored in user session. Correct ?

**Comment by mattgrayisok** [comment]
Yes, the data is only stored in the session so if the user's session expires their recently viewed history will also expire.

You can, of course, increase the PHP session timeout in order to prevent that from happening.

There's no way to maintain a user's session between browsers without requiring the user to log in and attaching the history to their user account, which is possible, but would introduce some interesting additional requirements for moving state between session and the user record when the user logs in.

**Comment by migmake** [comment]
OK thanks for the answer Matt.
I think I will have to developp my custom plugin then, recording the recently viewed data into the database.
